version: '3.8'
services:
  # app:
  #   build:
  #     context: .
  #     target: development
  #     dockerfile: ./Dockerfile
  #   container_name: app_fintrix
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   env_file:
  #     - docker.env
  #   ports:
  #     - '${PORT}:${PORT}'
  #   networks:
  #     - fintrix-network
  #   depends_on:
  #     - postgres
  #     - cache

  postgres:
    image: postgres:14.1-alpine
    container_name: db_fintrix
    env_file:
      - docker.env
    ports:
      - '5432:5432'
    networks:
      - fintrix-network
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data

  cache:
    image: redis:6.2-alpine
    container_name: cache_fintrix
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    networks:
      - fintrix-network
    volumes:
      - cache:/data

volumes:
  postgres:
    driver: local
  cache:
    driver: local

networks:
  fintrix-network:
