version: '3'
services:
  app:
    build: .
    container_name: app_fintrix
    command: npm run dev
    #command: npm run start:prod
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    env_file:
      - docker.env
    ports:
      - '3000:3000'
    networks:
      - fintrix-network
    depends_on:
      - postgres
      - cache

  postgres:
    image: postgres:14.1-alpine
    container_name: db_fintrix
    restart: always
    env_file:
      - docker.env
    ports:
      - '5432:5432'
    networks:
      - fintrix-network
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data

  cache:
    image: redis:6.2-alpine
    container_name: cache_fintrix
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    networks:
      - fintrix-network
    volumes:
      - cache:/data

volumes:
  postgres:
    driver: local
  cache:
    driver: local

networks:
  fintrix-network:
