version: '3.9'
services:
  db:
    image: postgres:14.1-alpine
    container_name: db_fintrix
    restart: always
    env_file:
      - docker.env
    ports:
      - '5432:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    networks:
      - fintrix

  cache:
    image: redis:6.2-alpine
    container_name: cache_fintrix
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
    networks:
      - fintrix

volumes:
  db:
    driver: local
  cache:
    driver: local

networks:
  fintrix:
    name: fintrix
    driver: bridge
